name: Verify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x' # This must match the Node version that is built into https://www.electronjs.org/
      -
        name: Verify
        run: npm install -p
        run: npm test
